spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://${SPRING_MYSQL_HOST:localhost}:3306/${SPRING_MYSQL_DB:code_interview}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${SPRING_MYSQL_USER:user}
    password: ${SPRING_MYSQL_PASSWORD:user}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace